#define SCREEN_W 700
#define SCREEN_H 700
#define CENTER_W SCREEN_W / 2
#define CENTER_H SCREEN_H / 2

#define SCREEN_W_POSITIVE_BOARD SCREEN_W - 25
#define SCREEN_W_NEGATIVE_BOARD 0
#define SCREEN_H_BOARD SCREEN_H - 25
#define SCREEN_H_NEGATIVE_BOARD 0

#define FRUIT_SPAWN_MIN_X SCREEN_W_NEGATIVE_BOARD + 20
#define FRUIT_SPAWN_MAX_X SCREEN_W - 20
#define FRUIT_SPAWN_MIN_Y SCREEN_H_NEGATIVE_BOARD + 40
#define FRUIT_SPAWN_MAX_Y SCREEN_H - 40

#define SNAKE_SPAWN_MIN_X CENTER_W / 2
#define SNAKE_SPAWN_MAX_X CENTER_W 
#define SNAKE_SPAWN_MIN_Y CENTER_H / 2
#define SNAKE_SPAWN_MAX_Y CENTER_H
